***********************************************************
    Прямое проектирование
    Plugin: Инструмент генерации ANSI DDL операторов (3.2.0 - 05-12-2009), Grandite

    Имя базы данных : "База данных"
    Source file   : "D:\Дмитрий\1Учеба\СДЕЛАТЬ!!!\3_kurs_2_semestr_BD\Лабы\Парамон\3_laba.sms"

    Generated on  : 29.04.2019 23:32:22
    Generated by Open ModelSphere Версия 3.2"
***********************************************************


***********************************************************
    CREATE STATEMENTS
***********************************************************


--/***********************************************************
--	TABLE 'NAKL'
--***********************************************************/

CREATE TABLE NAKL 
(
    NAKL_N INTEGER NOT NULL,
    NOMER_N INTEGER,
    N_DATA DATE,
    ITOGO DOUBLE PRECISION,
    MOL1 VARCHAR(50),
    OTDEL N_OTD INTEGER NOT NULL
);


--/***********************************************************
--	TABLE 'OTDEL'
--***********************************************************/

CREATE TABLE OTDEL 
(
    N_OTD INTEGER NOT NULL,
    NAZV_OT VARCHAR(50),
    MOL2 VARCHAR(50)
);


--/***********************************************************
--	TABLE 'STRN'
--***********************************************************/

CREATE TABLE STRN 
(
    NOM_STRN INTEGER NOT NULL,
    KOLVO INTEGER,
    STOIM DOUBLE PRECISION,
    NAKL NAKL_N INTEGER NOT NULL,
    TOVAR NOM_TOV INTEGER NOT NULL
);


--/***********************************************************
--	TABLE 'TOVAR'
--***********************************************************/

CREATE TABLE TOVAR 
(
    NOM_TOV INTEGER NOT NULL,
    NAZV VARCHAR(50),
    CENA DOUBLE PRECISION
);


--/***********************************************************
--	PRIMARY/UNIQUE KEY 'Primary key'
--***********************************************************/

ALTER TABLE NAKL 
  ADD CONSTRAINT Primary key PRIMARY KEY (
    NAKL_N)  ;
--/***********************************************************
--	PRIMARY/UNIQUE KEY 'Primary key'
--***********************************************************/

ALTER TABLE TOVAR 
  ADD CONSTRAINT Primary key PRIMARY KEY (
    NOM_TOV)  ;
--/***********************************************************
--	PRIMARY/UNIQUE KEY 'Primary key'
--***********************************************************/

ALTER TABLE STRN 
  ADD CONSTRAINT Primary key PRIMARY KEY (
    NAKL NAKL_N, NOM_STRN)  ;
--/***********************************************************
--	PRIMARY/UNIQUE KEY 'Primary key'
--***********************************************************/

ALTER TABLE OTDEL 
  ADD CONSTRAINT Primary key PRIMARY KEY (
    N_OTD)  ;


    

